/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Example GPIO Pin Control for STM32 GPIO API.
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdint.h>
#include "GPIOPeripheral.h"


int main(void)
{

	RCC_AHB1ENR_t volatile *const pClkCtrlReg     =  (RCC_AHB1ENR_t* ) (0x40023800 + 0x30);  //Clock control enable Reg address for AHB1 on which GPIOA is connected
	GPIOx_MODER_t volatile *const pGPIOAModeReg   =  (GPIOx_MODER_t* ) (0x40020000 + 0x00);  //GPIOA mode Reg address
	GPIOx_ODR_t volatile *const pGPIOAOutDataReg  =  (GPIOx_ODR_t* )   (0x40020000 + 0x14);  //GPIOA Output Data Reg address
	GPIOx_IDR_t volatile *const pGPIOAInDataReg   =  (GPIOx_IDR_t* )   (0x40020000 + 0x10);  //GPIOA Input Data Reg address

	pClkCtrlReg->GPIOA_EN = 1;  		//Enable clock for GPIOA in AHB1 Bus, via Clock control Reg of AHB1
	pGPIOAModeReg->PIN_5  = 1;         //Setting GPIOA pin 5 (LD2) mode to 01 (OUTPUT)
	pGPIOAModeReg->PIN_0  = 0;         //Setting GPIOA pin 0 to 00 (INPUT) mode
	pGPIOAModeReg->PIN_1 |= 1;         //Setting GPIOA pin 1 mode to 01 (OUTPUT)


	while(1)
	{
		if(pGPIOAInDataReg->IDR0)                      //If GPIO PA0 is HIGH
		{
			pGPIOAOutDataReg->ODR5 = 1;    //Set GPIOA pin-5 HIGH
			pGPIOAOutDataReg->ODR1 = 1;    //Set GPIOA pin-1 HIGH
		}
		else								//Else
		{
			pGPIOAOutDataReg->ODR5 = 0;   //Set GPIOA pin-5 LOW
			pGPIOAOutDataReg->ODR1 = 0;   //Set GPIOA pin-1 LOW
		}
	}
}
